baseURL: "https://rednafi.com"
title: Redowan's Reflections
theme: PaperMod
pluralizelisttitles: false

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: G-11NK905JK8
enableGitInfo: true

frontmatter:
  lastmod:
    - lastmod
    - :git
    - date

taxonomies:
  tag: tags

permalinks:
  posts: "/:section/:slug/"

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 20

params:
  env: production
  robotsNoIndex: false

  schema:
    publisherType: Person
    jobTitle: Software Engineer
    knowsAbout:
      - API Design
      - Databases
      - Distributed Systems
      - Go
      - Industrial Programming
      - Observability
      - Python
      - Software Engineering
    sameAs:
      - "https://github.com/rednafi"
      - "https://www.linkedin.com/in/rednafi/"
      - "https://bsky.app/profile/rednafi.com"
      - "https://fosstodon.org/@rednafi"

  description: >-
    Personal site of Redowan Delowar - a roving amateur fumbling through software, systems,
    and sundry.
  author: "Redowan Delowar"
  images: ["https://blob.rednafi.com/static/images/home/cover.png"]

  DateFormat: "January 2, 2006"
  defaultTheme: light
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  hideFooter: false
  ShowAllPagesInArchive: true
  ShowFullTextinRSS: true

  mainSections:
    - javascript
    - misc
    - zephyr
    - python
    - typescript
    - go
    - system

  assets:
    favicon: "https://blob.rednafi.com/static/images/home/favicon.webp"
    favicon16x16: "https://blob.rednafi.com/static/images/home/favicon.webp"
    favicon32x32: "https://blob.rednafi.com/static/images/home/favicon.webp"
    apple_touch_icon: "https://blob.rednafi.com/static/images/home/favicon.webp"
    safari_pinned_tab: "https://blob.rednafi.com/static/images/home/favicon.webp"
    disableFingerprinting: false
    disableHLJS: true

  label:
    icon: "https://blob.rednafi.com/static/images/home/favicon.webp"
    iconHeight: 23
    iconWidth: 23

  homeInfoParams:
    Title:
      Hi, I'm [Redowan](/about) <a href="/index.xml" title="RSS" aria-label="RSS"> <svg
      xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
      stroke="currentColor" stroke-width="2" height="23"> <path d="M4 11a9 9 0 0 1 9 9"/>
      <path d="M4 4a16 16 0 0 1 16 16"/> <circle cx="5" cy="19" r="1"/> </svg> </a>
    Content: >
      <div>
        A roving amateur fumbling through software, systems, & sundry.
      </div>

  social:
    twitter: "raboroham"

  analytics:
    google:
      SiteVerificationTag: "google-site-verification=GoibEK52o5Z7xpKQ7ppTd8bA_s1wQp5hcG7aIWPJJfk"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "cb037a09f985e313"
    naver:
      SiteVerificationTag: "097e5d3cd7b9e1ee3ad0addb5aaeea1b1a50be20"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    image: "https://blob.rednafi.com/static/images/home/cover.png"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 200
    threshold: 0.3
    minMatchCharLength: 2
    keys: ["title", "tags", "permalink", "summary", "content"]

menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 1
    - identifier: tags
      name: tags
      url: /tags/
      weight: 2
    - identifier: archive
      name: archive
      url: /archive/
      weight: 3
    - identifier: about
      name: about
      url: /about/
      weight: 4

  hamburger:
    - identifier: talks
      name: talks
      url: /talks/
      weight: 1
    - identifier: lore
      name: lore
      url: /lore/
      weight: 2
    - identifier: blogroll
      name: blogroll
      url: /blogroll/
      weight: 3
    - identifier: feed
      name: "2025"
      url: /feed/2025
      weight: 4

markup:
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    style: syntax-highlight
    tabWidth: 4

  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML", "RSS"]
  term: ["HTML", "RSS"]

security:
  funcs:
    getenv:
      - "^HUGO_"

module:
  mounts:
    - source: static
      target: static
